* N-phonon-interaction
A calculator for the phase space of N interacting phonons.

** The problem
Here I want to calculate how likely different classes of phonon (quantum of lattice vibration) interaction process are. Is 3-phonon scattering more likely compared to 4-phonon scattering for a certain phonon? A measure of this likelihood is the scattering phase space. This is a essentially a quantification of the amount of the restriction originating from energy and (quasi)-momentum conservation on different classes of phonon interactions. Below I explain further.

First, some notation. By *p* I denote a phonon mode. A phonon mode is fully described by a wavevector *q* and a polarization /s/. Phonon *1* is always my sampling phonon. That is, I want to know what the stattering phase space is for phonon *1*. Now imagine that we are describing all the /N/ phonon interaction processes. These are the possible interaction paths: phonon *1* can coalesce with $p \in {0, 1, ..., N - 2}$ phonons and decay into $N - p - 1$ phonons.
